services:

  mosquitto:
    build: ./mosquitto
    container_name: mosquitto
    environment:
      - MOSQ_USER=adm
      - MOSQ_PASS=sdf
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: always

  backend:
    build: ./backend
    container_name: backend
    environment:
      - MOSQUITTO_PASSWD=/mosquitto/config/passwd
      - MOSQUITTO_ACL=/mosquitto/config/acl
      - BROKER_USER=${MOSQ_USER:-backend-manager}
      - BROKER_PASS=${MOSQ_PASS:-supersecret}
    volumes:
      - ./mosquitto:/mosquitto
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3001:3001"
    depends_on:
      - mosquitto
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: always
